name: Deploy Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy-heroku:
    environment: ${{ github.ref_name }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files
        run: |
          touch .env
          echo API_KEY="${{ secrets.JWT_SECRET }}" >> .env
          cp .trvium/Dockerfile Dockerfile
